export const FETCH_PRODUCTS_START = "FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";

export const SORT_BY_BUTTON = "SORT_BY_BUTTON";
export const GET_END_OF_PAGE = "GET_END_OF_PAGE";
