export const FETCH_PRODUCTS_START = "FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const ADD_PRODUCTS = "ADD_PRODUCTS";

export const GET_SORTED_PRODUCTS = "GET_SORTED_PRODUCTS";
export const CREATE_RANDOM_NUMBERS = "CREATE_RANDOM_NUMBERS";
export const PUSH_SCROLLED_PAGE = "PUSH_SCROLLED_PAGE";
